### ISSUE TITLE
MediaMuxer crash

### ISSUE THREAD

**Issue by Reakleases** [Windsander/Android-UltimateGPUImage#16]
reproduced by sample on every device(except miui roms) on stop record:
`java.lang.IllegalStateException: Failed to stop the muxer
                                                                                                   at android.media.MediaMuxer.nativeStop(Native Method)
                                                                                                   at android.media.MediaMuxer.stop(MediaMuxer.java:245)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.stopMediaMuxer(XMediaMuxer.java:140)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.stopMuxer(XMediaMuxer.java:78)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder.handleStopRecording(TextureMovieEncoder.java:282)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder.access$400(TextureMovieEncoder.java:44)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:232)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder.run(TextureMovieEncoder.java:188)`

**Comment by Windsander** [comment]
thx, help a lot ;p

**Comment by AuxanoWeb** [comment]
Hi @Windsander 
I have same error as @Reakleases had.
Can you please give the solution to come out from this error?

**Comment by Windsander** [comment]
I see.  If I don't need to operate over this weekend. I will try to fix this problem.
Actually I'm working through like this 3 times..
So sorry for this.

**Comment by suchengjian** [comment]
I solve this problem.Crash in the stopMuxer() method of XMediaMuxer.
Add
try {
            videoThread.join();
            audioThread.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
before stopMediaMuxer();will solve this problem.

**Comment by Windsander** [comment]
fix now~  you can use 1.0.3 as instead~
