### ISSUE TITLE
IllegalStateException: Failed to stop the muxer

### ISSUE THREAD

**Issue by kagile** [Windsander/Android-UltimateGPUImage#17]
java.lang.IllegalStateException: Failed to stop the muxer
                                                                                                   at android.media.MediaMuxer.nativeStop(Native Method)
                                                                                                   at android.media.MediaMuxer.stop(MediaMuxer.java:245)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.stopMediaMuxer(XMediaMuxer.java:140)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.stopMuxer(XMediaMuxer.java:78)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder.handleStopRecording(TextureMovieEncoder.java:282)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder.access$400(TextureMovieEncoder.java:44)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:232)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                                   at cn.co.willow.android.ultimate.gpuimage.core_record_18.TextureMovieEncoder.run(TextureMovieEncoder.java:188)

**Comment by Windsander** [comment]
thanks, that's help a lot. ;p

**Comment by krupalagile** [comment]
@Windsander Can we expect a fix?

**Comment by Windsander** [comment]
I wish I can fix it quick. But my time is short, so many work today..
So, in this moment.. Sorry,  I can't..😐
But I will handle it as soon as I deal with my duty in company's project.

**Comment by lokeshmutyala** [comment]
For me crash happened if i change avconfig. initial video quality is very less so i want to change frame rate but muxer is crashing, how to change video quality without any error.

**Comment by suchengjian** [comment]
我解决了这个问题，发现了另一个问题。
我发现崩溃的发生是因为VideoEncoderThread和AudioEncoderThread实际启动（dequeueBuffer）在InputSurface.swapBuffers（）方法之后（这个方法会将数据填入Encorder的inputbuffer中）。 所以解决这个问题我们应该确保两个线程在InputSurface.swapBuffers（）之前启动。
另一个问题是stopMexuer。 我们将flge设置为退出，但是我们不等待两个endcode线程真正的退出，所以我们应该在停止mediamuxer之前调用Thread.join方法。

**Comment by Windsander** [comment]
嗯，实际上这个问题是由多个问题组成的，具体表现的是会导致crash。线程处理方面做了优化外，时间戳的错误录入也会导致这个问题。我重新优化了一下代码，并重新处理的视频帧时间戳的获取和音视频线程、音频采样线程和混合器线程的处理。这个问题就解决了。
