### ISSUE TITLE
Failed to stop the muxer. 

### ISSUE THREAD

**Issue by SanjayAndroidDev** [Windsander/Android-UltimateGPUImage#24]
Hello All, I am using this library for video recording. And it's working some device. But i got error in Samsung s6 device. While stop the recording. My exception log in below pasted.

E/MediaMuxer: stop() is called in invalid state 3
E/UncaughtException: java.lang.IllegalStateException: Failed to stop the muxer
                         at android.media.MediaMuxer.nativeStop(Native Method)
                         at android.media.MediaMuxer.stop(MediaMuxer.java:271)
                         at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.stopMediaMuxer(XMediaMuxer.java:183)
                         at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.checkTotalFinish(XMediaMuxer.java:95)
                         at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.access$100(XMediaMuxer.java:31)
                         at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer$1.onFinish(XMediaMuxer.java:81)
                         at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.VideoEncoder.autoEncodeFrame(VideoEncoder.java:188)
                         at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.VideoEncoder.run(VideoEncoder.java:137)
E/AndroidRuntime: FATAL EXCEPTION: Thread-16
                  Process: com.semicolon.survivorproject, PID: 21430
                  java.lang.IllegalStateException: Failed to stop the muxer
                      at android.media.MediaMuxer.nativeStop(Native Method)
                      at android.media.MediaMuxer.stop(MediaMuxer.java:271)
                      at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.stopMediaMuxer(XMediaMuxer.java:183)
                      at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.checkTotalFinish(XMediaMuxer.java:95)
                      at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer.access$100(XMediaMuxer.java:31)
                      at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.XMediaMuxer$1.onFinish(XMediaMuxer.java:81)
                      at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.VideoEncoder.autoEncodeFrame(VideoEncoder.java:188)
                      at cn.co.willow.android.ultimate.gpuimage.core_record_18.base_encoder.VideoEncoder.run(VideoEncoder.java:137)

**Comment by Windsander** [comment]
Thanks for you report.~
Have you upgrade to this lib's latest version ?~
The latest version is 1.0.3~
